### ISSUE TITLE
XSD might be wrong 

### ISSUE THREAD

**Issue by Rebecabfv** [apache/camel-website#1159]
### What happened?

I'm getting this error:
`org.xml.sax.SAXParseException; lineNumber: 4268; columnNumber: 51; cos-nonambig: "http://camel.apache.org/schema/spring":onFallback and "http://camel.apache.org/schema/spring":onFallback (or elements from their substitution group) violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two particles.`

It complains about duplicate "onFallback" in camel-spring.xsd.  I opened a question on Stack Overflow for it, follow it for more information: https://stackoverflow.com/questions/78156558/saxparseexception-with-camel-4/78158626#78158626

### Steps to reproduce

```
import com.google.common.io.Resources;

import javax.xml.XMLConstants;
import javax.xml.transform.Source;
import javax.xml.transform.stream.StreamSource;
import javax.xml.validation.SchemaFactory;
import java.io.ByteArrayInputStream;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;


public class Camel
{

    public static void main( String[] args ) throws Exception
    {
       SchemaFactory schemaFactory = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);

       List<Source> tmp = new ArrayList();

       String loc = "camel-spring.xsd";

       URL url = Resources.getResource(loc);
       byte[] bytes = Resources.toByteArray(url);
       StreamSource src = new StreamSource(new ByteArrayInputStream(bytes));
       tmp.add(src);

       schemaFactory.newSchema((Source[]) tmp.toArray(new Source[tmp.size()]));
    }
}
```
### Camel K version

Getting this error with all versions after Camel 4

**Comment by orpiske** [comment]
I am under the impression this problem is something that (seems to?) affects (be caused by?) Camel Core, but it's not very clear to me under what conditions you are experiencing it. 

Please [try to join our support chat on ZulipChat](https://camel.zulipchat.com/) - that's where most of the contributors involved with Core interact with the community. If the ZulipChat is not suitable for you, [we also have a few other ways you can use to reach out to the community and report problems](https://camel.apache.org/community/support/).

**Comment by orpiske** [comment]
FYI, there is already a discussion about this on ZulipChat: https://camel.zulipchat.com/#narrow/stream/364655-camel-core-dev/topic/Published.20schemas.
