### ISSUE TITLE
ckc release - wrong folder

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-website#676]
This does not look right with that svn import folder
<img width="549" alt="Screenshot 2021-11-16 at 10 51 10" src="https://user-images.githubusercontent.com/477100/141962595-1c113e48-7e8f-44cc-8128-a1a4dfbc358a.png">
.

**Comment by davsclaus** [comment]
@zregvart @valdar - I assume this is wrong, and that the release-0.11.0.md can be moved to where the other files are

**Comment by zregvart** [comment]
Hugo doesn't mind really, because the URL was given in the front matter:

https://github.com/apache/camel-website/blob/cd15067eac33d0abdd52f1b0535ba338b05365be/content/releases/ckc/svn%20import%20release/https:/dist.apache.org/repos/dist/release/camel/camel-kafka-connector/release-0.11.0.md?plain=1#L2

So it's published on the correct URL:

https://camel.apache.org/releases/ckc-0.11.0/

And updated on the downloads page:

https://camel.apache.org/download/#camel-kafka-connector

But it's poor form to have it differ from other release notes.

**Comment by valdar** [comment]
Sounds like there where a problem in the last release?

**Comment by valdar** [comment]
Yep, that is my fault!
I still don't know how I manage to do that though :dagger: 
Fixing it!
