### ISSUE TITLE
Links in Kamelets yaml are part of the link checker job

### ISSUE THREAD

**Issue by oscerd** [apache/camel-website#804]
In the last website build we have

```
Found invalid urls in camel-kamelets/next/jslt-action.html:
	Linked file at path /template.json does not exist!
Found invalid urls in camel-kamelets/next/jolt-transformation-action.html:
	Linked file at path /template.json does not exist!
Found invalid urls in camel-kamelets/next/json-schema-validator-action.html:
	Linked file at path /template.json does not exist!
Found invalid urls in camel-kamelets/next/json-patch-action.html:
	Linked file at path /template.json does not exist!
Found invalid urls in camel-kamelets/next/freemarker-template-action.html:
	Linked file at path /template.ftl does not exist!
Found invalid urls in camel-kamelets/next/jsonata-action.html:
	Linked file at path /template.spec does not exist!
ERROR: "check:links" exited with 1.
```

But those are just examples 
https://github.com/apache/camel-kamelets/blob/main/kamelets/jslt-action.kamelet.yaml#L42

We need to skip checking or workaround the problem.

cc @zregvart

**Comment by zregvart** [comment]
Fixed in https://github.com/apache/camel-website/commit/81dae36955704f533ecc5c3e0d852562abd41acf https://github.com/apache/camel-website/commit/51e5aa9d21cfa287c7280d91e956bf82dc8be303 https://github.com/apache/camel-kamelets/commit/060a19553314dad69c4b5ae37d86b6e70c4419da and https://github.com/apache/camel-kamelets/commit/7ef5a89f424a6b9310042bd022c3a7b3b68cb6a7
